services:
  whatsapp-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-service
    restart: unless-stopped
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./qrcode:/app/qrcode
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - DISPLAY=:99
      - NODE_OPTIONS=--max-old-space-size=4096
    shm_size: 2gb
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    # Command untuk menjalankan auth-whatsapp.ts, ganti sesuai kebutuhan
    # - Untuk autentikasi: ["bun", "src/auth-whatsapp.ts"]
    # - Untuk logout: ["bun", "src/logout-whatsapp.ts"]
    command: ["bun", "src/auth-whatsapp.ts"] 