version: '3'

services:
  upload-service:
    build:
      context: .
    container_name: upload-service
    ports:
      - "8789:8789"
    volumes:
      - shared-data-volume:/app/data
    restart: unless-stopped
    networks:
      - whatsapp-network
    env_file:
      - .env

volumes:
  shared-data-volume:
    external: true
    name: whatsapp-ai-gateway_data-volume

networks:
  whatsapp-network:
    external: true
    name: whatsapp-ai-gateway_whatsapp-network 