version: '3'

services:
  upload-service:
    build:
      context: .
    container_name: upload-service
    ports:
      - "8789:8789"
    volumes:
      - data-volume:/app/data
    restart: unless-stopped
    networks:
      - upload-network
    environment:
      - WHATSAPP_SERVICE_URL=http://host.docker.internal:8788

volumes:
  data-volume:

networks:
  upload-network:
    driver: bridge 